export const categories = [
  { id: "all", name: "All Projects" },
  { id: "acp", name: "ACP Sign Boards" },
  { id: "led", name: "LED Signage" },
  { id: "acrylic", name: "Acrylic Signs" },
  { id: "shopfront", name: "Shopfront Branding" },
  { id: "office", name: "Office Signage" },
  { id: "fabrication", name: "Fabrication Projects" },
];

export const projects = [
  // Old/Existing Projects
  {
    id: 1,
    title: "Wooden Texture Ceiling Cladding",
    category: "fabrication",
    image: "/images/project-1.jpeg",
    featured: false,
  },
  {
    id: 10,
    title: "Commercial Wayfinding Signs",
    category: "office",
    image: "/images/project-10.jpeg",
    featured: false,
  },
  {
    id: 11,
    title: "Stainless Steel Letters Board",
    category: "acrylic",
    image: "/images/project-11.jpeg",
    featured: false,
  },
  {
    id: 12,
    title: "Heavy Steel Signage Frame",
    category: "fabrication",
    image: "/images/project-12.jpeg",
    featured: false,
  },
  {
    id: 13,
    title: "Brushed Brass Corporate Wall",
    category: "acrylic",
    image: "/images/project-13.jpeg",
    featured: false,
  },
  {
    id: 14,
    title: "Showroom Front LED Channel",
    category: "led",
    image: "/images/project-14.jpeg",
    featured: false,
  },
  {
    id: 15,
    title: "Safety & Emergency Signages",
    category: "office",
    image: "/images/project-15.jpeg",
    featured: false,
  },
  {
    id: 16,
    title: "Aluminum Panel Cladding Work",
    category: "fabrication",
    image: "/images/project-16.jpeg",
    featured: false,
  },
  {
    id: 17,
    title: "Frosted Glass Privacy Graphics",
    category: "office",
    image: "/images/project-17.jpeg",
    featured: false,
  },
  {
    id: 18,
    title: "Digital Vinyl Glass Graphics",
    category: "shopfront",
    image: "/images/project-18.jpeg",
    featured: false,
  },
  {
    id: 19,
    title: "Exhibition Fabricated Canopy",
    category: "fabrication",
    image: "/images/project-19.jpeg",
    featured: false,
  },
  {
    id: 20,
    title: "Corporate Lobby LED Signage",
    category: "office",
    image: "/images/project-20.jpeg",
    featured: false,
  },
  {
    id: 21,
    title: "Bespoke Steel Signboard Frame",
    category: "fabrication",
    image: "/images/project-21.jpeg",
    featured: false,
  },
  {
    id: 22,
    title: "Automated Profile Metal Bending",
    category: "fabrication",
    image: "/images/project-22.jpeg",
    featured: false,
  },
  {
    id: 23,
    title: "High-Visibility Shop Board",
    category: "shopfront",
    image: "/images/project-23.jpeg",
    featured: false,
  },

  // New Renamed ACP Work Images
  {
    id: 24,
    title: "Shop Front Panel Cladding",
    category: "fabrication",
    image: "/images/acp-work-1.jpeg",
    featured: false,
  },
  {
    id: 25,
    title: "Commercial Exterior ACP Facade",
    category: "fabrication",
    image: "/images/acp-work-2.jpeg",
    featured: false,
  },
  {
    id: 26,
    title: "Residential ACP Cladding Work",
    category: "fabrication",
    image: "/images/acp-work-3.jpeg",
    featured: false,
  },
  {
    id: 27,
    title: "Automated Router Cut Facade Cladding",
    category: "fabrication",
    image: "/images/acp-work-4.jpeg",
    featured: false,
  },
  {
    id: 28,
    title: "Showroom Front ACP Facia Paneling",
    category: "fabrication",
    image: "/images/acp-work-5.jpeg",
    featured: false,
  },
  {
    id: 29,
    title: "Multi-Story Facade ACP Cladding",
    category: "fabrication",
    image: "/images/acp-work-6.jpeg",
    featured: false,
  },
  {
    id: 30,
    title: "Corporate Building ACP Cladding",
    category: "fabrication",
    image: "/images/acp-work-7.jpeg",
    featured: false,
  },
  {
    id: 31,
    title: "Weatherproof Aluminum Front Panel",
    category: "fabrication",
    image: "/images/acp-work-8.jpeg",
    featured: false,
  },
  {
    id: 32,
    title: "Premium Shop Front ACP Board",
    category: "acp",
    image: "/images/shop-front-board.jpeg",
    featured: false,
  },
  {
    id: 33,
    title: "Wooden Texture ACP Ceiling Cladding",
    category: "fabrication",
    image: "/images/acp-board.jpeg",
    featured: false,
  },

  // New LED & Other Category Projects
  {
    id: 34,
    title: "3D LED Backlit Glowing Sign",
    category: "led",
    image: "/images/glowing-board.jpeg",
    featured: true, // LED representative
  },
  {
    id: 35,
    title: "Outdoor Glow Lightbox Sign (New)",
    category: "led",
    image: "/images/glowing-board-2.jpeg",
    featured: false,
  },
  {
    id: 36,
    title: "Dual-Sided Glowing Flange Sign",
    category: "led",
    image: "/images/glowing-board-3.jpeg",
    featured: false,
  },
  {
    id: 37,
    title: "Showroom Front LED Channel Board",
    category: "led",
    image: "/images/glowing-board-4.jpeg",
    featured: false,
  },
  {
    id: 38,
    title: "Illuminated Retail Shopboard",
    category: "led",
    image: "/images/glowing-board-5.jpeg",
    featured: false,
  },
  {
    id: 39,
    title: "Pillar Backlit LED Board",
    category: "led",
    image: "/images/glowing-board-6.jpeg",
    featured: false,
  },
  {
    id: 40,
    title: "Commercial Corridor Glow Sign",
    category: "led",
    image: "/images/glowing-board-7.jpeg",
    featured: false,
  },
  {
    id: 41,
    title: "Laser-Cut Acrylic Name Plate",
    category: "acrylic",
    image: "/images/name-plate.jpeg",
    featured: true, // Acrylic representative
  },
  {
    id: 42,
    title: "Corporate Reception Logo Plaque",
    category: "office",
    image: "/images/name-plate-2.jpeg",
    featured: false,
  },
  {
    id: 43,
    title: "Custom Office Door Name Plate",
    category: "office",
    image: "/images/name-plate-3.jpeg",
    featured: true, // Office representative
  },
  {
    id: 44,
    title: "Solid Acrylic Letters Sign",
    category: "acrylic",
    image: "/images/name-plate-4.jpeg",
    featured: false,
  },
  {
    id: 45,
    title: "Brushed Metal Acrylic Board",
    category: "acrylic",
    image: "/images/name-plate-5.jpeg",
    featured: false,
  },
  {
    id: 46,
    title: "Exhibition Stall Logo Plate",
    category: "acrylic",
    image: "/images/name-plate-6.jpeg",
    featured: false,
  },
  {
    id: 47,
    title: "Frosted Acrylic Wall Plaque",
    category: "office",
    image: "/images/name-plate-7.jpeg",
    featured: false,
  },
  {
    id: 48,
    title: "Engraved Corporate Name Plate",
    category: "acrylic",
    image: "/images/name-plate-8.jpeg",
    featured: false,
  },
  {
    id: 49,
    title: "House Entrance Acrylic Plate",
    category: "acrylic",
    image: "/images/name-plate-9.jpeg",
    featured: false,
  },
  {
    id: 50,
    title: "Medical Clinic Cabin Sign",
    category: "office",
    image: "/images/name-plate-10.jpeg",
    featured: false,
  },
  {
    id: 51,
    title: "Executive Suite Office Plate",
    category: "acrylic",
    image: "/images/name-plate-11.jpeg",
    featured: false,
  },
  {
    id: 52,
    title: "High-Resolution Shop Flex Printing",
    category: "shopfront",
    image: "/images/flex-printing.jpeg",
    featured: true, // Shopfront representative
  },
  {
    id: 53,
    title: "Outdoor Promotion Flex Banner",
    category: "shopfront",
    image: "/images/flex-work.jpeg",
    featured: false,
  },
  {
    id: 54,
    title: "Showroom Windows Vinyl Graphic",
    category: "shopfront",
    image: "/images/shop-flex-board.jpeg",
    featured: false,
  },
  {
    id: 55,
    title: "Industrial PVC Roofing Fabrication",
    category: "fabrication",
    image: "/images/pvc-roofing-2.jpeg",
    featured: true, // Fabrication representative
  },
  {
    id: 56,
    title: "Shed Structure Fabrication Work",
    category: "fabrication",
    image: "/images/pvc-work.jpeg",
    featured: false,
  },
  {
    id: 57,
    title: "Fresh N Fold Laundry ACP Shopfront",
    category: "acp",
    image: "/images/fresh-n-fold.jpeg",
    featured: true,
  },
  {
    id: 58,
    title: "Om Estates 3D LED Entrance Gate Sign",
    category: "led",
    image: "/images/om-estates.jpeg",
    featured: true,
  },
  {
    id: 59,
    title: "Taneja Properties Rooftop LED Board",
    category: "led",
    image: "/images/taneja-properties.jpeg",
    featured: false,
  },
  {
    id: 60,
    title: "Custom Gold Mirror 3D Acrylic Letters",
    category: "acrylic",
    image: "/images/as-acrylic.jpeg",
    featured: false,
  },
  {
    id: 61,
    title: "Shree Tirupati Dham Gold Entrance Gate ACP Sign",
    category: "acp",
    image: "/images/tirupati-dham.jpeg",
    featured: true,
  },
  {
    id: 62,
    title: "Suncity Cinemas Halo Backlit LED Board",
    category: "led",
    image: "/images/suncity-cinemas.jpeg",
    featured: true,
  },
];

export const featuredProjects = projects.filter((p) => p.featured);
